### ISSUE TITLE
Strange menu bar behaviour in mac OS

### ISSUE THREAD

**Issue by mehtmehtsen** [GreyRook/siptop#7]
The icon in the mac OS menu bar appears to be quite wide. Normally its invisible, which in itself is not optimal. But when clicked, it shows some kind of giant logo (?) which is cropped to the height of the menu bar. 

<img width="1085" alt="Screenshot 2020-04-03 at 10 54 57" src="https://user-images.githubusercontent.com/10923446/78342492-abbda500-7599-11ea-9b91-d170481df09c.png">

**Comment by FlorianLudwig** [comment]
fixed in 092568cef5c4ccfc2ab2b98c93b05792c05e3f14
